services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Pass123' -Q 'SELECT 1' -b -h -1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    mem_limit: 4g  # Ensure SQL Server has enough memory

networks:
  app-network:
    driver: bridge

volumes:
  sqlserver-data:

   # docker-compose up --build